sudo: required
os:
  - linux
language: cpp
dist: bionic

services:
  - docker

jobs:
  include:
    - stage: builder container creation
      install: skip
      script: travis/builderContainerCreation.sh


# notifications:
#   slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
