sudo: required
language: cpp
dist: bionic
# install: true 

services:
  - docker

jobs:
  include:
    - stage: builder container creation
      install: skip
      script: travis/builderContainerCreation.sh


# notifications:
#   slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
